# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 04:01
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0043_auto_20190430_0356'),
        ('js_companies', '0002_auto_20190417_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='articles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='companies', to='aldryn_newsblog.Article', verbose_name='related articles'),
        ),
        migrations.AddField(
            model_name='company',
            name='newsblogjsrelatedplugins',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='related_companies', to='aldryn_newsblog.NewsBlogJSRelatedPlugin', verbose_name='related articles'),
        ),
    ]
