# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 08:05
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0012_auto_20190430_0804'),
        ('aldryn_people', '0036_auto_20190430_0747'),
        ('js_events', '0010_remove_event_companies'),
        ('js_companies', '0003_auto_20190430_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='events',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='companies', to='js_events.Event', verbose_name='events'),
        ),
        migrations.AddField(
            model_name='company',
            name='people',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='companies', to='aldryn_people.Person', verbose_name='people'),
        ),
        migrations.AddField(
            model_name='company',
            name='relatedpeopleplugin',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='related_companies', to='aldryn_people.RelatedPeoplePlugin', verbose_name='relatedpeopleplugin'),
        ),
        migrations.AddField(
            model_name='company',
            name='relatedservicesplugin',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='related_companies', to='js_services.RelatedServicesPlugin', verbose_name='relatedservicesplugin'),
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='companies', to='js_services.Service', verbose_name='services'),
        ),
        migrations.AlterField(
            model_name='company',
            name='articles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='companies', to='aldryn_newsblog.Article', verbose_name='articles'),
        ),
        migrations.AlterField(
            model_name='company',
            name='newsblogjsrelatedplugins',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='related_companies', to='aldryn_newsblog.NewsBlogJSRelatedPlugin', verbose_name='newsblogjsrelatedplugins'),
        ),
    ]
