# Generated by Django 2.2.28 on 2023-11-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_extentions', '0003_auto_20231106_1442'),
        ('js_companies', '0005_auto_20210312_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='categorisationextension',
            field=models.ManyToManyField(blank=True, related_name='companies', to='js_extentions.CategorisationExtension'),
        ),
    ]
